//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.41108.0
// 
namespace SoBrow.CodebitsService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileView", Namespace="http://schemas.datacontract.org/2004/07/SoBrow.Web")]
    public partial class ProfileView : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BlogField;
        
        private System.Collections.ObjectModel.Collection<string> FriendUidsField;
        
        private string IDField;
        
        private string NameField;
        
        private string PhotoUrlField;
        
        private string ProjectDescriptionField;
        
        private string ProjectNameField;
        
        private System.Collections.ObjectModel.Collection<string> SkillsField;
        
        private string TwitterField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Blog {
            get {
                return this.BlogField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogField, value) != true)) {
                    this.BlogField = value;
                    this.RaisePropertyChanged("Blog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.ObjectModel.Collection<string> FriendUids {
            get {
                return this.FriendUidsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendUidsField, value) != true)) {
                    this.FriendUidsField = value;
                    this.RaisePropertyChanged("FriendUids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PhotoUrl {
            get {
                return this.PhotoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoUrlField, value) != true)) {
                    this.PhotoUrlField = value;
                    this.RaisePropertyChanged("PhotoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProjectDescription {
            get {
                return this.ProjectDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectDescriptionField, value) != true)) {
                    this.ProjectDescriptionField = value;
                    this.RaisePropertyChanged("ProjectDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.ObjectModel.Collection<string> Skills {
            get {
                return this.SkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillsField, value) != true)) {
                    this.SkillsField = value;
                    this.RaisePropertyChanged("Skills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Twitter {
            get {
                return this.TwitterField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterField, value) != true)) {
                    this.TwitterField = value;
                    this.RaisePropertyChanged("Twitter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="CodebitsService.Codebits")]
    public interface Codebits {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Codebits/GetUserProfile", ReplyAction="urn:Codebits/GetUserProfileResponse")]
        System.IAsyncResult BeginGetUserProfile(string uid, System.AsyncCallback callback, object asyncState);
        
        SoBrow.CodebitsService.ProfileView EndGetUserProfile(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CodebitsChannel : SoBrow.CodebitsService.Codebits, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SoBrow.CodebitsService.ProfileView Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SoBrow.CodebitsService.ProfileView)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodebitsClient : System.ServiceModel.ClientBase<SoBrow.CodebitsService.Codebits>, SoBrow.CodebitsService.Codebits {
        
        private BeginOperationDelegate onBeginGetUserProfileDelegate;
        
        private EndOperationDelegate onEndGetUserProfileDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserProfileCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CodebitsClient() {
        }
        
        public CodebitsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodebitsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodebitsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodebitsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUserProfileCompletedEventArgs> GetUserProfileCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SoBrow.CodebitsService.Codebits.BeginGetUserProfile(string uid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserProfile(uid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoBrow.CodebitsService.ProfileView SoBrow.CodebitsService.Codebits.EndGetUserProfile(System.IAsyncResult result) {
            return base.Channel.EndGetUserProfile(result);
        }
        
        private System.IAsyncResult OnBeginGetUserProfile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            return ((SoBrow.CodebitsService.Codebits)(this)).BeginGetUserProfile(uid, callback, asyncState);
        }
        
        private object[] OnEndGetUserProfile(System.IAsyncResult result) {
            SoBrow.CodebitsService.ProfileView retVal = ((SoBrow.CodebitsService.Codebits)(this)).EndGetUserProfile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserProfileCompleted(object state) {
            if ((this.GetUserProfileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserProfileCompleted(this, new GetUserProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserProfileAsync(string uid) {
            this.GetUserProfileAsync(uid, null);
        }
        
        public void GetUserProfileAsync(string uid, object userState) {
            if ((this.onBeginGetUserProfileDelegate == null)) {
                this.onBeginGetUserProfileDelegate = new BeginOperationDelegate(this.OnBeginGetUserProfile);
            }
            if ((this.onEndGetUserProfileDelegate == null)) {
                this.onEndGetUserProfileDelegate = new EndOperationDelegate(this.OnEndGetUserProfile);
            }
            if ((this.onGetUserProfileCompletedDelegate == null)) {
                this.onGetUserProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserProfileCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserProfileDelegate, new object[] {
                        uid}, this.onEndGetUserProfileDelegate, this.onGetUserProfileCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SoBrow.CodebitsService.Codebits CreateChannel() {
            return new CodebitsClientChannel(this);
        }
        
        private class CodebitsClientChannel : ChannelBase<SoBrow.CodebitsService.Codebits>, SoBrow.CodebitsService.Codebits {
            
            public CodebitsClientChannel(System.ServiceModel.ClientBase<SoBrow.CodebitsService.Codebits> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUserProfile(string uid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = uid;
                System.IAsyncResult _result = base.BeginInvoke("GetUserProfile", _args, callback, asyncState);
                return _result;
            }
            
            public SoBrow.CodebitsService.ProfileView EndGetUserProfile(System.IAsyncResult result) {
                object[] _args = new object[0];
                SoBrow.CodebitsService.ProfileView _result = ((SoBrow.CodebitsService.ProfileView)(base.EndInvoke("GetUserProfile", _args, result)));
                return _result;
            }
        }
    }
}
